// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atlgexrvqoophlwacxvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0bGdleHJ2cW9vcGhsd2FjeHZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MTEyMDksImV4cCI6MjA3MDI4NzIwOX0.RXHYIcqGlOd7_2ILwLO2TlVBcU1IwLGBXGc0-Gn_EY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});